name: Deploy

on:  
  push:
    branches:
      - main
    paths:
      - '.github/workflows/deployment.yml'

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v4
        with: 
          registry: ghcr.io
          username: ${{ vars.GH_USERNAME }}
          password: ${{ secrets.GH_PAT }} 

      - name: Build and push all to GHCR        
        run: |
          echo "Full build and push to GHCR"
          git submodule update --init --recursive 
          docker compose build
          docker compose push
          
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ vars.VPS_HOST }}
          username: ${{ vars.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            echo "${{ secrets.GH_PAT }}" | docker login ghcr.io \
              -u "${{ vars.GH_USERNAME }}" \
              --password-stdin

            cd projects/conduit-container
            docker compose pull
            docker compose up -d --force-recreate
