name: Deploy

on: 
  workflow_run:
    workflows:
      - Build and push Conduit backend
      - Build and push Conduit frontend 
    types: [completed]   
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v4
        with: 
          registry: ghcr.io
          username: ${{ vars.GH_USERNAME }}
          password: ${{ secrets.GH_PAT }} 

      - name: Build and push all to GHCR        
        run: |
          echo "Full build and push to GHCR"
          git submodule update --init --recursive 
          docker compose build
          docker compose push
          
      - name: Deploy
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ vars.VPS_HOST }}
          username: ${{ vars.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            echo "${{ secrets.GH_PAT }}" | docker login ghcr.io \
              -u "${{ vars.GH_USERNAME }}" \
              --password-stdin

            cd projects/conduit-container
            docker compose pull
            docker compose up -d 

      # - name: Deploy
      #   run: |          
      #     EVENT="${{ github.event.workflow_run.name }}"
      #     SHA="${{ github.event.workflow_run.head_sha }}"
              
      #     if [ -z "$SHA" ]; then
      #       echo "Broken SHA. Exiting..."
      #       exit 1

      #     echo "1"
      #       elif [ "$EVENT" = "Deploying Conduit backend" ]; then   
      #         IMAGE="ghcr.io/${{ vars.GH_USERNAME }}/${{ vars.BACKEND_IMAGE_NAME }}:$SHA"
      #         docker pull "$IMAGE"
      #         docker rm -f ${{ vars.BACKEND_IMAGE_NAME }} || true
      #         docker compose run -d ${{ vars.BACKEND_IMAGE_NAME }}
      #         echo "2"
      #       elif [ "$EVENT" = "Deploying Conduit frontend" ]; then
      #         IMAGE="ghcr.io/${{ vars.GH_USERNAME }}/${{ vars.FRONTEND_IMAGE_NAME }}:$SHA"
      #         docker pull "$IMAGE"
      #         docker rm -f ${{ vars.FRONTEND_IMAGE_NAME }} || true
      #         docker compose run -d ${{ vars.FRONTEND_IMAGE_NAME }}
      #         echo "3"  
      #       else
      #         echo "Unsupportet event: $EVENT"
      #       fi
